# Use postgres/example user/password credentials
version: '3.1'

services:
  dw2:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=dw2
      - POSTGRES_USER=dw2
      - POSTGRES_DB=dw2
    ports:
      - 5432:5432
